// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolderToWorkspace() {
  return window['go']['main']['App']['AddFolderToWorkspace']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function ExportAsImagePath() {
  return window['go']['main']['App']['ExportAsImagePath']();
}

export function ExportAsImagePathWithName(arg1) {
  return window['go']['main']['App']['ExportAsImagePathWithName'](arg1);
}

export function ExportAsTxt(arg1) {
  return window['go']['main']['App']['ExportAsTxt'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetMultiFolderFileTree(arg1) {
  return window['go']['main']['App']['GetMultiFolderFileTree'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadFileContent(arg1) {
  return window['go']['main']['App']['LoadFileContent'](arg1);
}

export function LoadWorkspaceFile(arg1) {
  return window['go']['main']['App']['LoadWorkspaceFile'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveImageData(arg1, arg2) {
  return window['go']['main']['App']['SaveImageData'](arg1, arg2);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SetEditorWidth(arg1) {
  return window['go']['main']['App']['SetEditorWidth'](arg1);
}

export function SetLastWorkspace(arg1) {
  return window['go']['main']['App']['SetLastWorkspace'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximized() {
  return window['go']['main']['App']['WindowIsMaximized']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowQuit() {
  return window['go']['main']['App']['WindowQuit']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}
